=== simranbeauty/WebTechnology/q5/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="student_records">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first_name" type="xs:string"/>
                    <xs:element name="middle_name" type="xs:string" minOccurs="0"/>
                    <xs:element name="last_name" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="email">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[^@]+@[^\.]+\..+"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="phone">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="(98|97)[0-9]{8}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="address" maxOccurs="2">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="type" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="permanent"/>
                            <xs:enumeration value="temporary"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="DOB">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="datePattern">
                      <xs:attribute name="type" use="required">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="AD"/>
                            <xs:enumeration value="BS"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="rollno" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniqueRollNo">
      <xs:selector xpath="student"/>
      <xs:field xpath="@rollno"/>
    </xs:unique>
  </xs:element>
  <xs:simpleType name="datePattern">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== simranbeauty/WebTechnology/q5/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<student_records xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="students.xsd">
    <student rollno="S101">
        <name>
            <first_name>Rohan</first_name>
            <middle_name>Kumar</middle_name>
            <last_name>Sharma</last_name>
        </name>
        <email>rohan.sharma@example.com</email>
        <phone>9841234567</phone>
        <address type="permanent">Kathmandu, Nepal</address>
        <address type="temporary">Lalitpur, Nepal</address>
        <DOB type="AD">2004-05-14</DOB>
    </student>
    <student rollno="S102">
        <name>
            <first_name>Aayusha</first_name>
            <last_name>Shrestha</last_name>
        </name>
        <email>aayusha@domain.org</email>
        <phone>9745678901</phone>
        <address type="permanent">Pokhara, Nepal</address> 
        <DOB type="BS">2061-02-25</DOB>
    </student>
</student_records>
